name: Deploy Express.js Application to EC2

on:
  push:
    branches:
      - main
      - release-*

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          check-latest: true

      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "."
          target: "~/MOTION-BEAT-Backend/backend"

      - name: Restart application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/MOTION-BEAT-Backend/backend
            npm install
            pm2 restart all

      - name: Send notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: "deployments"
          SLACK_COLOR: ${{ job.status == 'success' && 'good' || 'danger' }}
          SLACK_MESSAGE: "${{ github.repository }} deployment ${{ job.status }}!"
          SLACK_TITLE: "Deployment Status"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
